tegra: ventana: fix build break caused by suspend
67b96e77464be05ca9e444cd2f21023b80fa08fc added suspend support but
doesn't seem to build. There's a missing <mach/suspend.h> include,
but even then the following pops:

arch/arm/mach-tegra/board-ventana-power.c:143: error: unknown field 'dram_suspend' specified in initializer
arch/arm/mach-tegra/board-ventana-power.c:144: error: unknown field 'core_off' specified in initializer

So just remove those. Please re-add when syncing in whatever other
suspend changes are pending out-of-tree that adds these fields.

Signed-off-by: Olof Johansson <olof@lixom.net>